import type { Ticket } from './types';

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'tk-1',
    fileId: 'file-rfp-aws',
    title: 'RFP 要件整理',
    content: '顧客X社のAWS保守RFPを精読。SLA 99.9%、24/7一次対応、月次レポート必須。',
    color: 'blue',
    x: 60,
    y: 120,
    width: 280,
    height: 160,
    createdBy: 'Noa',
    createdAt: minutesAgo(180),
    updatedAt: minutesAgo(22),
    activity: [
      { id: 'a1', kind: 'created', actor: 'Noa', actorKind: 'human', message: 'Ticket created', createdAt: minutesAgo(180) },
      { id: 'a2', kind: 'comment', actor: 'Claude', actorKind: 'ai_agent', message: 'SLA項目を抽出しました', createdAt: minutesAgo(120) },
      { id: 'a3', kind: 'edit', actor: 'Noa', actorKind: 'human', message: 'content updated', createdAt: minutesAgo(22) },
    ],
  },
  {
    id: 'tk-2',
    fileId: 'file-rfp-aws',
    title: '懸念点: DR構成未定',
    content: 'RFPに復旧目標 (RPO/RTO) の記載なし。ヒアリング必要。Multi-AZ前提かMulti-Regionか。',
    color: 'rose',
    x: 400,
    y: 100,
    width: 280,
    height: 170,
    createdBy: 'Noa',
    createdAt: minutesAgo(140),
    updatedAt: minutesAgo(140),
    activity: [
      { id: 'a4', kind: 'created', actor: 'Claude', actorKind: 'ai_agent', message: 'AIが抽出した懸念点', createdAt: minutesAgo(140) },
    ],
  },
  {
    id: 'tk-3',
    fileId: 'file-rfp-aws',
    title: 'CloudWatch 閾値設計',
    content: 'CPU>80% 5min / Memory>85% / 5xx rate>1% / Disk>75% を初期値。環境別チューニング後続。',
    color: 'emerald',
    x: 740,
    y: 140,
    width: 280,
    height: 170,
    createdBy: 'Claude',
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(30),
    activity: [
      { id: 'a5', kind: 'ai_action', actor: 'Claude', actorKind: 'ai_agent', message: 'CloudWatch設計案を生成', createdAt: minutesAgo(90) },
      { id: 'a6', kind: 'comment', actor: 'Noa', actorKind: 'human', message: 'Disk閾値は80%でいきたい', createdAt: minutesAgo(30) },
    ],
  },
  {
    id: 'tk-4',
    fileId: 'file-rfp-aws',
    title: '月次レポート雛形',
    content: 'SLA達成率 / インシデント件数 / 変更件数 / 改善提案3件 を基本フォーマットに。',
    color: 'amber',
    x: 60,
    y: 330,
    width: 280,
    height: 150,
    createdBy: 'Noa',
    createdAt: minutesAgo(60),
    updatedAt: minutesAgo(60),
    activity: [
      { id: 'a7', kind: 'created', actor: 'Noa', actorKind: 'human', message: 'Ticket created', createdAt: minutesAgo(60) },
    ],
  },
  {
    id: 'tk-5',
    fileId: 'file-rfp-aws',
    title: '運用体制',
    content: '一次: 社内SRE 2名ローテ / 二次: 専門ベンダ契約 / エスカレ: CTO直。',
    color: 'violet',
    x: 400,
    y: 320,
    width: 280,
    height: 150,
    createdBy: 'Noa',
    createdAt: minutesAgo(50),
    updatedAt: minutesAgo(50),
    activity: [
      { id: 'a8', kind: 'created', actor: 'Noa', actorKind: 'human', message: 'Ticket created', createdAt: minutesAgo(50) },
    ],
  },
  {
    id: 'tk-6',
    fileId: 'file-rfp-aws',
    title: 'メモ: コスト見積',
    content: '保守人件費 + ツール(Datadog/PagerDuty) + 予備工数。ベンダ見積待ち。',
    color: 'neutral',
    x: 740,
    y: 360,
    width: 280,
    height: 130,
    createdBy: 'Noa',
    createdAt: minutesAgo(20),
    updatedAt: minutesAgo(20),
    activity: [
      { id: 'a9', kind: 'created', actor: 'Noa', actorKind: 'human', message: 'Ticket created', createdAt: minutesAgo(20) },
    ],
  },
];
